# Generated by Django 5.2.9 on 2025-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='outro',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
