# Generated by Django 5.2.9 on 2025-12-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidato_outro'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='teste',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
