# Generated by Django 5.2.9 on 2025-12-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidato_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='outro',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='teste',
        ),
    ]
