# Generated by Django 5.2.9 on 2025-12-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_candidato_outro_remove_candidato_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='anotacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
