# Generated by Django 5.2.9 on 2025-12-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_candidato_curriculo_alter_candidato_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='email',
            field=models.CharField(default='lol'),
            preserve_default=False,
        ),
    ]
