# Generated by Django 5.2.9 on 2025-12-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_candidato_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='status',
            field=models.CharField(choices=[('SUBMETIDO', 'Cadastro submetido'), ('ENTREVISTA', 'Selecionado para entrevista'), ('APROVADO', 'Resultado final: aprovado'), ('REPROVADO', 'Resultado final: reprovado'), ('NAO_COMPARECEU', 'Resultado final: não compareceu')], default='SUBMETIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
