# Generated by Django 5.2.9 on 2025-12-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_candidato_status_alter_candidato_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrevistaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas', models.JSONField(blank=True, default=dict)),
                ('decisao', models.CharField(choices=[('DECIDIR_DEPOIS', 'Decidir depois'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('NAO_COMPARECEU', 'Não compareceu')], default='DECIDIR_DEPOIS', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrevista', to='core.candidato')),
            ],
        ),
    ]
