# Generated by Django 5.2.9 on 2025-12-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_entrevistaavaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevistaavaliacao',
            name='entrevistado',
            field=models.BooleanField(default=False),
        ),
    ]
